from typing import Protocol

from elevator_control.domain import entities as e
from elevator_control.domain.enums import EventStatus, EventType, ServiceRequestStatus


class LiftRepository(Protocol):
    def get_by_id(self, lift_id: int) -> e.Lift | None: ...
    def list_paginated(self, offset: int, limit: int) -> tuple[list[e.Lift], int]: ...
    def create(self, lift: e.Lift) -> e.Lift: ...
    def update(self, lift: e.Lift) -> e.Lift | None: ...
    def delete(self, lift_id: int) -> bool: ...


class SensorRepository(Protocol):
    def get_by_id(self, sensor_id: int) -> e.Sensor | None: ...
    def list_by_lift(self, lift_id: int) -> list[e.Sensor]: ...
    def list_all(self) -> list[e.Sensor]: ...
    def create(self, sensor: e.Sensor) -> e.Sensor: ...
    def update(self, sensor: e.Sensor) -> e.Sensor | None: ...
    def delete(self, sensor_id: int) -> bool: ...


class EventRepository(Protocol):
    def get_by_id(self, event_id: int) -> e.Event | None: ...
    def list_filtered(
        self,
        offset: int,
        limit: int,
        lift_id: int | None,
        status: EventStatus | None,
        event_type: EventType | None,
    ) -> tuple[list[e.Event], int]: ...
    def create(self, event: e.Event) -> e.Event: ...
    def update(self, event: e.Event) -> e.Event | None: ...
    def has_open_critical_for_lift(self, lift_id: int) -> bool: ...


class ServiceRequestRepository(Protocol):
    def get_by_id(self, request_id: int) -> e.ServiceRequest | None: ...
    def list_filtered(
        self,
        offset: int,
        limit: int,
        lift_id: int | None,
        status: ServiceRequestStatus | None,
    ) -> tuple[list[e.ServiceRequest], int]: ...
    def create(self, req: e.ServiceRequest) -> e.ServiceRequest: ...
    def update(self, req: e.ServiceRequest) -> e.ServiceRequest | None: ...
    def delete(self, request_id: int) -> bool: ...


class TechnicianRepository(Protocol):
    def get_by_id(self, tech_id: int) -> e.Technician | None: ...
    def list_paginated(self, offset: int, limit: int) -> tuple[list[e.Technician], int]: ...
    def create(self, tech: e.Technician) -> e.Technician: ...
    def update(self, tech: e.Technician) -> e.Technician | None: ...
    def delete(self, tech_id: int) -> bool: ...


class ReportRepository(Protocol):
    def get_by_id(self, report_id: int) -> e.Report | None: ...
    def list_paginated(self, offset: int, limit: int) -> tuple[list[e.Report], int]: ...
    def create(self, report: e.Report) -> e.Report: ...
    def update(self, report: e.Report) -> e.Report | None: ...
    def delete(self, report_id: int) -> bool: ...
